export default {
    Aesthetic: "The aesthetic person sees the highest value in form and harmony. Each experience is judged from the standpoint of grace, symmetry, or fit. He regards life as a procession of events; each event enjoyed for its own sake. He need not be a creative   Copyright IMX Inc. 2009. Portions Copyrighted Peter T. Klassen, PhD, Leon Pomeroy PhD. and Robert S. Hartman PhD. All Rights Reserved. No part of this publication may be reproduced or distributed in any form or by any means without the prior written consent of the publisher. 4 artist, nor need he be decadent; he is aesthetic if he but finds his chief interest in the beauty of life. The aesthetic attitude is, in a sense, diametrically opposed to the theoretical; the former is concerned with the diversity, and the latter with the understanding of experience. The aesthetic person either chooses, with Keats, to consider truth as equivalent to beauty, or agrees with Mencken, that, ‘to make a thing charming is a million times more important than to make it true’. In the economic sphere the aesthetic person sees the process of manufacturing, advertising, and trade as a wholesale destruction of the values most important to him.",
    
    Altruistic: "The highest value for the altruistic person is love of people. In this dimension it is the altruistic or philanthropic aspect of love that is measured. The altruistic person prizes other persons as ends, and is therefore herself kind, sympathetic, and unselfish. She is likely to find the theoretical or economic attitudes cold and inhuman. In contrast to the political type, the altruistic person regards love as itself the only suitable form of human relationship.",

    Economic: "The economic person is characteristically interested in what is useful. Based originally upon the satisfaction of bodily needs (self-preservation), the interest in utilities develops to embrace the practical affairs of the business world—the production, marketing, and consumption of goods, the elaboration of credit, and the accumulation of tangible wealth. This type is thoroughly practical and conforms well to the prevailing stereotype of the businessperson. \n More than perhaps any other, the economic attitude frequently comes into conflict with other values. The economic person wants education to be practical, and regards unapplied knowledge [often sought by the theoretical person] as waste. Great feats of engineering and application result from the practical demands economic people make upon science and theory. The value of utility likewise conflicts with the aesthetic value except when art serves commercial ends. In his personal life the economic person is likely to confuse luxury with beauty. In his relations with people he is more likely to be interested in surpassing them in wealth than in dominating them (political attitude) or in serving them (altruistic attitude). In some instances he may have regard for the regulatory attitudes, but inclines to consider it as a means to rewards of wealth, prosperity, and other tangible blessings.",

    Individualistic: "The individualistic person seeks to be separate and independent. Her desire is to stand out, to express her uniqueness and be granted freedom over her actions to champion her own bearing. Unlike the political attitude, the individualistic person seeks neither power nor control of others or the environment in general. She is only concerned with controlling her own fate and protecting her own sovereignty. The individual person rails against his subjugation by any external force and when she feels so her only focus becomes her own emancipation.",

    Political: "The political person is interested primarily in power and control. His activities are not necessarily within the narrow field of politics, but whatever his vocation, he   Copyright IMX Inc. 2009. Portions Copyrighted Peter T. Klassen, PhD, Leon Pomeroy PhD. and Robert S. Hartman PhD. All Rights Reserved. No part of this publication may be reproduced or distributed in any form or by any means without the prior written consent of the publisher. 5 betrays himself as a Machtmensch (i.e., control freak.) Leaders in any field generally have high power and control values. Since competition and struggle play a large part in all life, many philosophers have seen power as the most universal and most fundamental of motives. There are, however, certain personalities in whom the desire for a direct expression of this motive is uppermost, who wish above all else for personal power, influence, and renown.",

    Regulatory: "The highest value of the regulatory person may be called unity. She is mystical and seeks to comprehend the cosmos as a whole and to relate herself to its embracing totality. The regulatory person is one whose mental attitude is directed towards achieving structure and is permanently directed to the creation of the highest and absolutely satisfying value of order and constitution. Some of this type finds their life’s value in the affirmation of life’s systems or processes and in active participation therein. The ‘traditionalist’ seeks to unite herself with a higher order – to be one with the system.",

    Theoretical: "The dominant interest of the theoretical person is the discovery of truth. In the pursuit of this goal he characteristically takes a ‘cognitive’ attitude, one that looks for identities and differences; one that divests itself of judgments regarding the beauty or utility of objects, and seeks only to observe, reason and understand. Since the interests of the theoretical are empirical, critical, and rational, he is necessarily an intellectualist, frequently a scientist or philosopher. His chief aim in life is to gain, order and systematize his knowledge.",
}